modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="forerunner_bridges_and_barriers"
version="1.0.0"
displayName="Forerunner Bridges and Barriers"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Arturo Enrique Rosas Gutiérrez (RGMods)"
description='''
Puentes y barreras de luz dura como la tecnología forerunner de Halo
'''

[[dependencies.forerunner_bridges_and_barriers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




